### ISSUE TITLE
Alertmanager STS does not automatically reload with updates to configmap

### ISSUE THREAD

**Issue by logyball** [crdsonnet/alertmanager-libsonnet#4]
When updating a configmap using this library, we do not "tell" Alertmanager that it should reload to get the new config.  We have to either wait until the pods naturally recycle or manually restart them to gain the new config.

I propose we annotate the STS with a hash of the configmap that can be automatically created with the md5 hash of the contents of the configmap.  We could use the utility function [configMapVolumeMount](https://jsonnet-libs.github.io/k8s-libsonnet/1.30/apps/v1/statefulSet/#fn-configmapvolumemount) from the k8s-libsonnet library to achieve this.

**Comment by Duologic** [comment]
I don't think this is true, there is a watch container looking for config changes, it reload the AM instance with an HTTP call: https://github.com/crdsonnet/alertmanager-libsonnet/blob/master/alertmanagerKube/main.libsonnet#L89

**Comment by logyball** [comment]
> I don't think this is true, there is a watch container looking for config changes, it reload the AM instance with an HTTP call: https://github.com/crdsonnet/alertmanager-libsonnet/blob/master/alertmanagerKube/main.libsonnet#L89

Right, this will reload the actual instance of AM, but an update to the configmap itself won't trigger the contents of the configmap to be re-mounted as a volume to the pod, will it?

**Comment by Duologic** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically 😉

**Comment by logyball** [comment]
well ill be darned

**Comment by logyball** [comment]
closing, as I misunderstood fundamentally how this worked 🤦
